// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAArEjpoCX1Eksn3trAC-oq-14OffI5WfM',
    appId: '1:851101712300:web:9c93e8e83eee40c7d90409',
    messagingSenderId: '851101712300',
    projectId: 'be-fit-7878d',
    authDomain: 'be-fit-7878d.firebaseapp.com',
    storageBucket: 'be-fit-7878d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-zVYDFTzHAOnEjUFtfivYrrUOOyAxh_g',
    appId: '1:851101712300:android:7d5db6361832c7b4d90409',
    messagingSenderId: '851101712300',
    projectId: 'be-fit-7878d',
    storageBucket: 'be-fit-7878d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbRCPEtl9D7Wh5uPKhsHg6z4ygMrwXnY',
    appId: '1:851101712300:ios:c83a60e9ee8e37cad90409',
    messagingSenderId: '851101712300',
    projectId: 'be-fit-7878d',
    storageBucket: 'be-fit-7878d.appspot.com',
    iosBundleId: 'com.example.beFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXbRCPEtl9D7Wh5uPKhsHg6z4ygMrwXnY',
    appId: '1:851101712300:ios:c83a60e9ee8e37cad90409',
    messagingSenderId: '851101712300',
    projectId: 'be-fit-7878d',
    storageBucket: 'be-fit-7878d.appspot.com',
    iosBundleId: 'com.example.beFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAArEjpoCX1Eksn3trAC-oq-14OffI5WfM',
    appId: '1:851101712300:web:8aeb3728712c060ed90409',
    messagingSenderId: '851101712300',
    projectId: 'be-fit-7878d',
    authDomain: 'be-fit-7878d.firebaseapp.com',
    storageBucket: 'be-fit-7878d.appspot.com',
  );
}
